@startuml "Logout"
skin rose
actor "Người Dùng" as User
participant "Trình Duyệt" as Browser
participant "Hệ Thống" as Server

User -> Browser: 1. Yêu cầu đăng xuất
Browser -> Server: 2. Thông báo đăng xuất
Server -> Server: 3. Hủy phiên đăng nhập
Server -> Browser: 4. Đăng xuất thành công
Browser -> User: 5. Trở về trang đăng nhập
