@startuml
skinparam entity {
    stereotypeBackgroundColor #FF9800
    attributeTextColor #000000
}
entity Admin {
    int ID PK
    string Name
    string Email
    string Phone
    string Role
    int TaskForceID FK
}

entity TaskForce {
    int ID PK
    string Name
    datetime EstablishedDate
    string Function
    string Size
}

entity Pandemic {
    int ID PK
    string Name
    datetime StartDate
    string AffectedRegions
    int InfectedCases
}

entity Vaccine {
    int ID PK
    string Name
    datetime ApprovalDate
    string Type
    string BatchNumber
    int PandemicID FK
}

entity CityProvince {
    int ID PK
    string Name
    int Population
    int Area
    string Coordinates
}

entity Statistics {
    int ID PK
    datetime UpdatedAt
    int InfectedCases
    int Deaths
    int Recoveries
    int TodayCases
    int CityID FK
}

entity TreatmentArea {
    int ID PK
    string Name
    int Capacity
    string Address
    string TreatmentType
    int CityID FK
}

entity Patient {
    int ID PK
    string Name
    int Age
    string Gender
    string Status
}

entity Relative {
    int ID PK
    string Name
    string Relationship
    string Phone
    int PatientID FK
}

entity Vaccine_city {
    int ID PK
    int VaccineID FK
    int CityID FK
    int Amount
}

entity Vaccine_city_treatmentarea {
    int ID PK
    int VaccineCityId FK
    int TreatmentAreaId FK
    int Amount
}

entity Vaccine_patient {
    int ID PK
    int VaccineCityTreatmentAreaId FK
    int PatientId FK
    datetime VaccinatedOn not null
}

Admin ||--o{ TaskForce : manages
TaskForce ||--|{ Pandemic : responds_to
Pandemic ||--o{ Vaccine : includes_vaccine
Pandemic ||--o{ CityProvince : impacts
Vaccine ||--o{ Vaccine_city : allocate
CityProvince ||--o{ TreatmentArea : has
CityProvince ||--o{ Statistics : reports_statistics
CityProvince ||--o{ Vaccine_city : receives
Vaccine_city ||--o{ Vaccine_city_treatmentarea : allocates_to
TreatmentArea ||--o{ Vaccine_city_treatmentarea : receives
TreatmentArea ||--o{ Patient : treats
Patient ||--o{ Relative : has
Vaccine_city_treatmentarea ||--o{ Vaccine_patient: allocates_to
Patient ||--o{ Vaccine_patient : has_vaccination_history

@enduml