@startuml
skin rose
actor "Người Dùng" as User
participant "Trình Duyệt" as Browser
participant "Hệ Thống" as Server

User -> Browser: 1. Yêu cầu xem danh sách dịch bệnh
Browser -> Server: 2. Gửi yêu cầu xem danh sách
Server -> Server: 3. Lấy dữ liệu danh sách dịch bệnh
Server -> Browser: 4. Gửi danh sách dịch bệnh
Browser -> User: 5. Hiển thị danh sách dịch bệnh

@enduml
